### ISSUE TITLE
kubernetes_manifest cannot be deployed together with argoCD CRD

### ISSUE THREAD

**Issue by Thumbiceq** [lablabs/terraform-helm-argocd#5]
kubernetes_manifest resources is checked before applying. The problem here is that since ArgoCD CRD is not deployed yet kubernetes does not know `Kind: Application` which is defined in kubernetes_manifest resource. 

Workaround: in first Terraform run set `self_managed` to false, and kubernetes_manifest will not be applied. In the second run set `self_managed` to true. This will work.

It did not work with kubernetes provider `v2.4.1`

**Comment by martinhaus** [comment]
Solved in module refactor in #9
